### ISSUE TITLE
Optimize calculations of Point's and Size's

### ISSUE THREAD

**Issue by justalemon** [justalemon/GGOV#2]
We need to make the calculations of the elements on-screen clean as possible.

You can see that [over here](https://github.com/justalemon/GGOV/blob/master/GGO.Common/Configuration.cs#L134-L149) we are duplicating the function even if we can convert form Point to Size and viceversa.

**Comment by mwanchap** [comment]
I've submitted a PR for this issue :) #5

**Comment by justalemon** [comment]
Fixed by #5
