### ISSUE TITLE
Add the player information

### ISSUE THREAD

**Issue by justalemon** [justalemon/GGOV#3]
The player information is a must for the stable release, it should be on the bottom right corner. There is some progress on the [playerinfo](https://github.com/justalemon/GGOV/tree/playerinfo) branch.

You can start with the old [0.x branch](https://github.com/justalemon/GGOV/tree/oldbeta) but it needs to be rewriten.

This is how it looks on the 0.x branch:

![10072840431151874048_20180730194629_1](https://user-images.githubusercontent.com/11861253/46432906-cb1a0e80-c725-11e8-90e5-3b62b50ded80.png)

This is how it should look on the bottom right:

![saoaggoe05_09](https://user-images.githubusercontent.com/11861253/46432528-dc165000-c724-11e8-8096-7a789066518b.jpg)

![vlcsnap-2018-09-25-09h52m47s847](https://user-images.githubusercontent.com/11861253/46561274-571a6a80-c8cd-11e8-95a3-d1c6adb4d739.png)

![saoaggoe05_12](https://user-images.githubusercontent.com/11861253/46432548-ecc6c600-c724-11e8-8d8f-bdb28fe547c9.jpg)

**Comment by NamStalker** [comment]
I'd like to look at this.

**Comment by justalemon** [comment]
Go ahead @NamStalker! I just merged my WIP changes on the master branch.

**Comment by NamStalker** [comment]
Just to clarify, what should be going in the bottom part of the player info? It looks like it was used for support of dual wielding? Edit: Nevermind, silly question, must be tired lol.

**Comment by justalemon** [comment]
First row is health and player name
Second row is primary weapon
Third row is sidearm or melee weapons

**Comment by justalemon** [comment]
Closed on #10 and fixed by subsequent commits.
