### ISSUE TITLE
Add "over the head" mark for dead peds

### ISSUE THREAD

**Issue by justalemon** [justalemon/GGOV#7]
A not-so-easy task: Adding a near 1:1 version of the Dead marks.

They should be over the head and not on the center of mass. I remember that @ahk1221 said:

![image](https://user-images.githubusercontent.com/11861253/46560748-44069b00-c8cb-11e8-8b62-b869b1be893a.png)

At the end, they should look like the ones in the anime:

![capture](https://user-images.githubusercontent.com/11861253/46560471-474d5700-c8ca-11e8-8865-a3cce2ea29fd.PNG)
![vlcsnap-2018-09-25-09h40m02s083](https://user-images.githubusercontent.com/11861253/46560472-474d5700-c8ca-11e8-98d1-4d02fa080de5.png)

**Comment by NamStalker** [comment]
I'd like to look at this one too.

**Comment by NamStalker** [comment]
Didn't have a backup of GTA before the update this morning, so my ScriptHook is dead and I can't test changes. Will postpone development until ScriptHook is updated to work with newest patch.

**Comment by justalemon** [comment]
@NamStalker If you have the Steam version, follow this guide to revert the update:
https://forums.gta5-mods.com/topic/18253/how-to-download-old-exes-after-update-steam

**Comment by NamStalker** [comment]
Oh thanks for linking this, I will try when I get off of work.

**Comment by justalemon** [comment]
For the RGSC/Rockstar edition, install this: http://patches.rockstargames.com/prod/gtav/Launcher_EFIGS/GTA_V_Launcher_1_0_1365_0.exe

**Comment by justalemon** [comment]
Closed by #12
